# Generated by Django 4.2.20 on 2025-04-22 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_characteristic_community_question_topic_survey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='dashboard.characteristic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='dashboard.topic'),
        ),
    ]
