# Generated by Django 4.2.20 on 2025-04-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_question_characteristic_alter_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='characteristic',
        ),
        migrations.AddField(
            model_name='question',
            name='characteristics',
            field=models.ManyToManyField(related_name='questions', to='dashboard.characteristic'),
        ),
    ]
