# Generated by Django 4.2.20 on 2025-04-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_question_characteristic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.community')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.survey')),
            ],
            options={
                'unique_together': {('community', 'survey')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='response',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.assessment'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('assessment', 'question')},
        ),
        migrations.RemoveField(
            model_name='response',
            name='community',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
    ]
