"""
Django settings for rrd project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import platform
from shutil import which
import os
from logging.handlers import RotatingFileHandler


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tpdj&mb3+*&k_w_i#e&watt__=l6%l%a3*1b)zwcam5182)hoa"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# Update ALLOWED_HOSTS to include the SDP server
ALLOWED_HOSTS = [
    "localhost", 
    "127.0.0.1",
    "[::1]",
    "sdp.boisestate.edu", 
]

# Tailwind CSS Configurations


TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]

# Set the path to the npm executable dynamically
NPM_BIN_PATH = which("npm") 

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "RuralResilienceDashboard", # Django app
    # "RuralResilienceDashboard.apps.RuralresiliencedashboardConfig", # Include the app to project
    "dashboard.apps.DashboardConfig",  # Include the app to project
    "tailwind",
    "theme",
    # "django_browser_reload", # (No longer needed, only for development)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_browser_reload.middleware.BrowserReloadMiddleware", # (No longer needed, only for development)
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

# compress static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "rrd.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rrd.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'djangocs481db'),
        'USER': os.environ.get('POSTGRES_USER', 'djangocs481admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'Djangocs481password'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
}

# DATABASE_ROUTERS = ['rrd.db_router.ResilienceRouter']

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC" # Change to your timezone if needed (e.g., "America/Boise"), this time is reflected in the database and containers
TIME_ZONE = "America/Boise" 

USE_I18N = True

USE_TZ = True

# Set the HTML root as Git repo name
# APP_ROOT = "s25-horde"

# Update the APP_ROOT to be a configurable URL root to not need SDP root (e.g. /s25-horde/)
APP_ROOT = os.getenv("APP_ROOT", "")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# STATIC_URL = "static/"

# Update STATIC_URL to point to the correct location
STATIC_URL = f"{APP_ROOT}static/" if APP_ROOT else "static/"

# Add STATIC_ROOT to point to the correct location
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Add static files directories to collect static files from
# STATICFILES_DIRS = [
#     BASE_DIR / "static",  # Adjust this path as necessary
# ]

# STATICFILES_DIRS = [
#     BASE_DIR / 'backend' / 'theme' / 'static',  # Adjust this path as necessary
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Add CSRF authentication for SDP server
CSRF_TRUSTED_ORIGINS = ['https://*.127.0.0.1', 'https://sdp.boisestate.edu']


# Handles logging errors to a file
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django_errors.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,             # Keep 5 old logs
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
